# -*- coding: utf-8 -*-
"""keras_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vmDG_EDU6Jinj0NR6QgpXoTL-DZ_y8_k
"""

import keras 
import numpy as np
import matplotlib as plt

from keras.models import Sequential

model = Sequential()

from keras.layers import Dense

model.add(Dense(units=64, activation = 'relu'))
model.add(Dense(units=10, activation = 'softmax'))





"""# To configure its learning process : """

model.compile(loss = 'categorical_crossentropy', optimizer = 'sgd', metrics = ['accuracy'])

"""# To further configure your optmizer"""

model.compile(loss= keras.losses.categorical_crossentropy, optimizer = keras.optimizers.SGD(learning_rate = 0.01, momentum = 0.9, nesterov = True))

"""#Iteration of training data in batches"""

model.fit(x_train, y_train, epochs = 5, batch_size = 32)

loss_and_metrics = model.evaluate(x_test, y_test, batch_size = 128)

"""# Generate prediction on new data"""

classes = model.predict(x_test, batch_size = 128)
